### ISSUE TITLE
Usage for mixed amplicons of a shared template

### ISSUE THREAD

**Issue by splaisan** [avierstr/amplicon_sorter#16]
Hi,
I have a mixture of amplicons coming from the differential amplification of isoforms of the same template.
I want to sequence them on ONT and split them in  bins of highly similar reads with a count of reads per bin.
Ideally, I would also like to have the consensus of each bin (or best representative read)
Some amplicons will congtain region(s) (exons) and other will not but they should all start and end with the PCR primers (I will filter the reads to ensure this and reorient them accordingly).
Is you software adapted to this task or if not what would you suggest to use here?
thanks for the info
Stephane

**Comment by avierstr** [comment]
Hi Stephane,
Amplicon_sorter should work perfect for this and sort all this reads out and make a consensus for each bin.  You don't have to reorient the reads so that they all are forward, because amplicon_sorter compares them as forward and reverse to find the best match.  It is possible that the consensus sequence will be a 3'-5' and not a 5'-3' consensus because the program does not know the correct orientation.
Best regards,
Andy

**Comment by splaisan** [comment]
Thanks a lot Andy, this is perfect and I will try it as soon as I get the reads.
Cheers
